Oren
simcard0000/se-webring pull request #24
Opened 2022-08-10 02:02 UTC by OrenLeung

_To add your site to the webring, you must be a **current student or an alum** of the [undergraduate Software Engineering program at the University of Waterloo](https://uwaterloo.ca/future-students/programs/software-engineering) (Waterloo, ON, Canada)._

**Full Name:** Oren Leung

**Cohort Year:** 2025

**Full website URL:** www.orenleung.com

_So we know you're human:_

**LinkedIn or a similar profile:** [\<insert other profile URL here>](https://www.linkedin.com/in/oren-leung/)

_Don't forget to also add your entry to the end of the_ `allSites` _array in the_ `se-webring.js` _file (name, year, personal website), and to add the_ `add site` _label to your pull request. Assign as a reviewer either_ @simcard0000 _or_ @janakitti.

2022-08-10 02:02 UTC, OrenLeung commented
@simcard0000

2022-08-12 18:24 UTC, simcard0000 requested changes
Oren plz link back to webring

2022-10-23 04:06 UTC, OrenLeung commented
Hi, @simcard0000 thanks for setting this webring up! <3 I have implemented the suggested changes. Thanks.

2022-10-23 04:13 UTC, simcard0000 approved these changes

2022-10-23 04:15 UTC, merged